import { motion } from "framer-motion";
import { 
  Search, 
  Bot, 
  Zap, 
  Shield, 
  FileText, 
  BarChart3,
  Globe,
  Lock
} from "lucide-react";

const features = [
  {
    icon: Search,
    title: "Deep Plagiarism Detection",
    description: "Compare against billions of web pages, academic papers, and publications.",
  },
  {
    icon: Bot,
    title: "AI Content Detection",
    description: "Advanced algorithms to identify content generated by GPT, Claude, and other AI models.",
  },
  {
    icon: Zap,
    title: "Instant Analysis",
    description: "Get comprehensive results in seconds, not minutes. Optimized for speed.",
  },
  {
    icon: Shield,
    title: "Academic Standards",
    description: "Meets the requirements of universities and educational institutions worldwide.",
  },
  {
    icon: FileText,
    title: "Multiple Formats",
    description: "Support for PDF, Word documents, and plain text files up to 10MB.",
  },
  {
    icon: BarChart3,
    title: "Detailed Reports",
    description: "Exportable reports with highlighted sections and source citations.",
  },
  {
    icon: Globe,
    title: "Multi-Language",
    description: "Support for over 30 languages with accurate detection across all.",
  },
  {
    icon: Lock,
    title: "Privacy First",
    description: "Your documents are encrypted and never stored after analysis.",
  },
];

export const FeaturesSection = () => {
  return (
    <section id="features" className="py-20 bg-background">
      <div className="container mx-auto px-4 sm:px-6">
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          transition={{ duration: 0.5 }}
          className="text-center mb-16"
        >
          <h2 className="text-3xl sm:text-4xl font-bold text-foreground mb-4">
            Powerful Features
          </h2>
          <p className="text-lg text-muted-foreground max-w-2xl mx-auto">
            Everything you need to ensure document integrity and originality
          </p>
        </motion.div>

        <div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-6">
          {features.map((feature, index) => (
            <motion.div
              key={index}
              initial={{ opacity: 0, y: 20 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              transition={{ duration: 0.5, delay: index * 0.1 }}
              className="group p-6 rounded-2xl bg-card border border-border hover:border-accent/30 hover:shadow-lg transition-all duration-300"
            >
              <div className="w-12 h-12 rounded-xl bg-accent/10 flex items-center justify-center mb-4 group-hover:bg-accent/20 transition-colors">
                <feature.icon className="w-6 h-6 text-accent" />
              </div>
              <h3 className="text-lg font-semibold text-foreground mb-2">
                {feature.title}
              </h3>
              <p className="text-sm text-muted-foreground">
                {feature.description}
              </p>
            </motion.div>
          ))}
        </div>
      </div>
    </section>
  );
};
